"""add_rules_tables

Revision ID: a3c6041bf6fa
Revises: 001_initial_schema
Create Date: 2026-02-18 08:10:54.308458
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3c6041bf6fa'
down_revision: Union[str, Sequence[str], None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rulesets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.Column('org_id', sa.String(length=100), nullable=True),
    sa.Column('location_id', sa.String(length=100), nullable=True),
    sa.Column('campaign_id', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rulesets_campaign_id'), 'rulesets', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_rulesets_location_id'), 'rulesets', ['location_id'], unique=False)
    op.create_index(op.f('ix_rulesets_org_id'), 'rulesets', ['org_id'], unique=False)
    op.create_index(op.f('ix_rulesets_tenant_id'), 'rulesets', ['tenant_id'], unique=False)
    op.create_table('rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ruleset_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ruleset_id'], ['rulesets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rules')
    op.drop_index(op.f('ix_rulesets_tenant_id'), table_name='rulesets')
    op.drop_index(op.f('ix_rulesets_org_id'), table_name='rulesets')
    op.drop_index(op.f('ix_rulesets_location_id'), table_name='rulesets')
    op.drop_index(op.f('ix_rulesets_campaign_id'), table_name='rulesets')
    op.drop_table('rulesets')
    # ### end Alembic commands ###
